config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	def index
	@articles = Article.all
	end
	def show
	@article = Article.find(params[:id])
	end
	def new
		@article = Article.new
	end
	def edit
	@article = Article.find(params[:id])
	end
	def create
	  @article = Article.new(article_params)
	  if @article.save
	    redirect_to @article
	  else
	    render 'new'
		  end
	end
	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end
	def destroy
	  @article = Article.find(params[:id])
	  @article.destroy
	 
	  redirect_to articles_path
	end
	private
	def article_params
	params.require(:article).permit(:title, :text)
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    respond_to do |format|
        format.html { redirect_to article_path(@article) }
        format.js 
    end
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
        format.html { redirect_to article_path(@article) }
        format.js 
    end
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_comments.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <input type="submit" class="btn btn-primary" value="Create Article">
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<br>
</br>
<br>
</br>
<div class="container panel panel-default">
	<h1 class="panel-heading">Edit article</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', articles_path, class: "btn btn-primary glyphicon glyphicon-arrow-left" %>
	<br>
	</br>
</div>

app/views/articles/index.html.erb
<h3></h3>
<%= link_to ' New article', new_article_path, class: "btn btn-primary glyphicon glyphicon-plus-sign"%>
<br>
</br>
<br>
</br>
<div class="container panel panel-default">
  <h1 class="panel-heading">Listing Articles</h1>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td>
        <%= link_to 'Show', article_path(article), class: "btn btn-primary" %> | 
        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary glyphicon glyphicon-edit" %> | 
        <%= link_to 'Destroy', article_path(article), class: "btn btn-primary glyphicon glyphicon-trash",
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/articles/new.html.erb
<br>
</br>
<br>
</br>
<div class="container panel panel-default">
	<h1 class="panel-heading">New article</h1>
	 
	<%= render 'form' %>
	 
	<%= link_to 'Back', articles_path, class: "btn btn-primary glyphicon glyphicon-arrow-left" %>
	<br>
	</br>
</div>

app/views/articles/show.html.erb
<br>
</br>
<br>
</br>
<div class="container panel panel-default">
  <p>
    <h3 class="panel-heading">Title : <%= @article.title %></h3>
  </p>
  <p>
    <h3 class="panel-heading">Text : <%= @article.text %></h3>
  </p>
  <h3 class="panel-heading">Comments:</h3>
  <div id="comments">
  	<%= render @article.comments %>
  </div>
  <h3 class="panel-heading">Add a comment:</h3>
  <%= render 'comments/form' %>
  <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary glyphicon glyphicon-edit" %> |
  <%= link_to 'Back', articles_path, class: "btn btn-primary glyphicon glyphicon-arrow-left" %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= comment.id %>">
<p>
  <strong>Commenter:</strong>
  	<%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
	<%= comment.body %>
</p>
<p>
	
	  <%= link_to 'Destroy Comment', [comment.article, comment], class: "btn btn-primary",
               method: :delete, remote: true,
               data: { confirm: 'Are you sure?' } %>
</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build], remote: true) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <input type="submit" class="btn btn-primary" value="Create Comment">
  </p>
<% end %>

app/views/comments/create.js.erb
$("#comments").html("<%=j render @article.comments %>");
$('#comment_commenter').val('');
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$("#<%= @comment.id %>").hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
        </p>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/_modal.html.erb
<!-- <div class="container">
<h2>Modal Login Example</h2>
Trigger the modal with a button
<button type="button" class="btn btn-default btn-lg" id="myBtn">Login</button>
-->
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2>Log in</h2>
        <form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|>
        <form class="new_user" id="new_user" action="/users/sign_in" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="QgRqxn/xUQ7q6IArn+dWj4GVP4UNxE9dfah4szvY0tE+O/wKhBFpJEwZAA749PyefRQBYSKNkz94Vp6IysLOJg==" />
          <div class="field">
            <label for="user_email">Email</label><br />
            <input autofocus="autofocus" type="email" value="" name="user[email]" id="user_email" />
          </div>

          <div class="field">
            <label for="user_password">Password</label><br />
            <input autocomplete="off" type="password" name="user[password]" id="user_password" />
          </div>

            <div class="field">
              <input name="user[remember_me]" type="hidden" value="0" /><input type="checkbox" value="1" name="user[remember_me]" id="user_remember_me" />
              <label for="user_remember_me">Remember me</label>
            </div>

          <div class="actions">
            <input type="submit" name="commit" value="Log in" />
          </div>
        </form>
        <end>
        <a href="/users/sign_up" type="button" id="btn1" class="btn btn-primary" data-toggle="modal" data-target="#myModal1" data-dismiss="modal">Sign up</a><br />
        <a href="/users/password/new">Forgot your password?</a><br />
      </div>
    </div>
  </div>
</div> 

app/views/welcome/_modal1.html.erb
<div class="modal fade" id="myModal1" role="dialog">
  <div class="modal-dialog">
	  <div class="modal-content">
    	<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2>Sign up</h2>
				<form class="new_user" id="new_user" action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="7MHSNUPwq1ummFd8ylVc9NUtygVBOnuHvDRWoaMwI+D2cjvFjE0tLbmmvsZ2W9hcfhIeR3Y7DXt+lj5In7xo/A==" />
			    <div class="field">
				    <label for="user_email">Email</label><br />
				    <input autofocus="autofocus" type="email" value="" name="user[email]" id="user_email" />
				  </div>
				  <div class="field">
				    <label for="user_password">Password</label>
				    <em>(8 characters minimum)</em>
				    <br />
				    <input autocomplete="off" type="password" name="user[password]" id="user_password" />
				  </div>
				  <div class="field">
				    <label for="user_password_confirmation">Password confirmation</label><br />
				    <input autocomplete="off" type="password" name="user[password_confirmation]" id="user_password_confirmation" />
				  </div>
				  <div class="actions">
				    <input type="submit" name="commit" value="Sign up" />
				  </div>
				</form>
				<a href="/users/sign_in" type="button" id="btn" class="btn btn-primary" data-toggle="modal" data-target="#myModal" data-dismiss="modal">Log in</a><br />
			</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<%= render 'modal' %>
<!-- Button trigger modal -->
<button type="button" id="btn" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
 Login
</button>

<!-- Button trigger modal -->
<button type="button" id="btn1" class="btn btn-primary" data-toggle="modal" data-target="#myModal1">
 Sign Up
</button>
<%= render 'modal1' %>

<%= link_to ' Show all articles', articles_path, class: "btn btn-primary glyphicon glyphicon-th-list" %>